
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Simulator:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and test multiple destinations
      run: |
        xcrun simctl list 
        xcodebuild clean build test -workspace App/QuizApp.xcworkspace -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" -destination "platform=iOS Simulator,name=iPhone 13" -destination "platform=iOS Simulator,name=iPhone 14" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO 
